version: "3.1"
services:
  db-first:
    container_name: sql1
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "5000:1433"
    volumes:
      - sharedata:/var/opt/mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Abc1233345678"
volumes:
  sharedata: