version: "3.1"
services:
  db-sencond:
    container_name: sql2
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "5000:1433"
    volumes:
      - db-first_sharedata:/var/opt/mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Abc1233345678"
volumes:
  db-first_sharedata:
    external: true